version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - 3000:3000
      - 5000:5000
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/local/bundle
    env_file:
      - .envdir/development/database
      - .envdir/development/web
    depends_on:
      - db
    command: foreman start
    tty: true
    stdin_open: true

  db:
    image: postgres:9.6
    env_file:
      - .envdir/development/database
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
    env_file:
      - .envdir/development/database
    ports:
      - 5432

volumes:
  gem_cache:
  postgres:
